import type { Metadata } from 'next'
import { Roboto } from 'next/font/google';
import './globals.css'

// font
export const roboto = Roboto({
    weight: ['100','300', '400', '500', '700', '900' ],
    subsets: ['vietnamese', 'latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>{children}</body>
    </html>
  )
}
